---
- name: Update packages list
  apt:
    update_cache: yes

- name: Make sure interfaces.d included in common configuration in proper order
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      source {{ config_vlan_interfaces }}
      source {{ config_vxlan_interfaces }}
      source {{ config_vxlan_bridge }}
      source {{ config_seed_interfaces }}
    state: present
  notify:
  - restart networking

- name: Install bridge-utils
  ansible.builtin.package:
    name: bridge-utils
    state: present

- name: Get network configuration from file
  include_vars:
    file: "{{ network_config_path }}"
    name: network_configuration
