---
- name: Update packages list
  apt:
    update_cache: yes

- name: Make sure interfaces.d included in common configuration
  become: yes
  lineinfile:
    path: /etc/network/interfaces
    line: "source /etc/network/interfaces.d/*.cfg"
    state: present
  notify:
  - restart networking

- name: Get network configuration from file
  include_vars:
    file: "{{ network_config_path }}"
    name: network_configuration
