---
- name: Install iptables-persistent
  ansible.builtin.apt:
    update_cache: true
    name: iptables-persistent
    state: present

- name: Check if iptables rule for DOCKER-USER already exists
  ansible.builtin.command: iptables -C DOCKER-USER -j ACCEPT
  register: iptables_rule_check
  changed_when: false
  ignore_errors: true

- name: Modify iptables to accept traffic for DOCKER-USER chain
  ansible.builtin.command: iptables -I DOCKER-USER -j ACCEPT
  when: iptables_rule_check is failed

- name: Save iptables to recover it after the reboot
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
  changed_when: false
