---
- import_tasks: ../common/tasks/main.yaml

# Considering management/regional cluster is already deployed when DHCP servers are defined
# to remove all seed node infrastructure which blocks all incoming traffic to the router:
# https://docs.docker.com/network/iptables/
- name: Check if the bootstrap was finished
  set_fact:
    bootstrap_finished: '{{ dhcp_servers | length  > 0 }}'

- name: Configuring Bridge based at vlan iface
  template:
    src: "{{ config_seed_interfaces_template }}"
    dest: /etc/network/interfaces.d/bridge.cfg
    owner: root
    group: root
    mode: 0644
  become: true
  when: not is_router or (is_router and not bootstrap_finished)
  notify:
  - restart networking

- name: Check if br0 bridge exists
  shell: brctl show br0
  register: bridge_exists
  ignore_errors: true
  when: is_router and bootstrap_finished

- name: Remove br0 bridge
  include_tasks: remove_bridge.yaml
  when: is_router and bootstrap_finished and bridge_exists is not failed

# See https://docs.docker.com/network/iptables/#docker-on-a-router
- name: Configure iptables
  include_tasks: configure_iptables.yaml
  when: is_router and bootstrap_finished

- name: Make sure that networking and isc-dhcp-relay were restarted
  meta: flush_handlers

- name: Create seed user
  ansible.builtin.user:
    name: "{{ seed_username }}"
    state: present
    shell: /bin/bash
    groups: sudo
    append: yes

- name: Deploy SSH Public Key
  ansible.posix.authorized_key:
    user: "{{ seed_username }}"
    state: present
    key: "{{ lookup('file', '{{ ansible_ssh_public_key_file }}') }}"

- name: Passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
