---
- name: Remove br0 bridge
  ansible.builtin.command: ip link delete dev br0
  changed_when: false
  notify:
    - Restart networking

- name: Ensure bridge configuration is removed
  ansible.builtin.file:
    state: absent
    path: "{{ config_seed_interfaces }}"
  notify:
    - Restart networking
    - Restart isc-dhcp-relay
