---
- name: Installing Squid proxy
  apt:
    name: "squid"
    state: "present"

- name: Configuring Squid proxy
  template:
    src: "{{ config_squid_proxy_template }}"
    dest: /etc/squid/squid.conf
    mode: 0644
  notify:
    - restart squid proxy

- name: Ensure Squid proxy is running
  service:
    name: squid
    state: started
