---
- name: Installing Squid proxy
  ansible.builtin.apt:
    name: "squid"
    state: "present"

- name: Configuring Squid proxy
  ansible.builtin.template:
    src: "{{ config_squid_proxy_template }}"
    dest: /etc/squid/squid.conf
    mode: 0644
  notify:
    - Restart squid proxy

- name: Ensure Squid proxy is running
  ansible.builtin.service:
    name: squid
    state: started
