---
- name: Install chrony
  apt:
    name: "chrony"
    state: "present"

- name: Configure chrony
  template:
    src: "{{ config_chrony_template }}"
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart chrony

- name: Enable chrony
  service:
    name: chrony
    state: started
    enabled: true
