---
- name: Install chrony
  ansible.builtin.apt:
    name: "chrony"
    state: "present"

- name: Configure chrony
  ansible.builtin.template:
    src: "{{ config_chrony_template }}"
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart chrony

- name: Enable chrony
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true
