---
- name: Installing ISC-DHCP-Relay
  apt:
    name: "isc-dhcp-relay"
    state: "present"

- name: Configuring ISC-DHCP-Relay
  template:
    src: "{{ config_dhcp_relay_template }}"
    dest: /etc/default/isc-dhcp-relay
    mode: 0644
  notify:
    - restart isc-dhcp-relay

- name: Ensure dhcp relay is running
  service:
    name: isc-dhcp-relay
    state: started
